### ISSUE TITLE
Фильтры. Регионы. Вывести в списке регионы 3-го и следующих уровней [НЕ ДЕЛАЕМ]

### ISSUE THREAD

**Issue by el-pirata-bueno** [Demonided/diplom_search_vacancies#182]
ЗАДАЧА НЕАКТУАЛЬНА
![Image](https://github.com/Demonided/diplom_search_vacancies/assets/110718064/f1284303-1415-4a50-8140-fb77798620c9)

1. Вывести в списке регионов все пункты из запроса areas с непустым parent_id (рекурсивный запрос)
2. Проверить, что при пустых полях Страна и Регион после выбора Региона автоматически заполняется Страна. Рекурсивно проходим обратно по parent_id в списке areas. Там, где parent_id = null, подставляем, как страну.
3. Проверить корректную работу поиска с фильтром (после выбора региона 3-го и ниже уровней).

**Comment by Demonided** [comment]
Да оставляем предыдущий вариант, он валидный
